### ISSUE TITLE
Admin - Members list page improvements

### ISSUE THREAD

**Issue by EmCousin** [EmCousin/pkp#113]
Can you provide some improvements to the admin members page so that :
- The avatar of each member is shown at the left of their name
- The birthdate is displayed
- The action buttons are closer to each other

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/9846489/83501969-33a02c80-a4c1-11ea-972f-b7776a811628.png">

**Comment by silvadaniele** [comment]
If it is like the image, is already done by you!

**Comment by EmCousin** [comment]
Oh, right. Done then!
