### ISSUE TITLE
Course form - enhancements

### ISSUE THREAD

**Issue by EmCousin** [EmCousin/pkp#31]
Based on the following screenshot, you are tasked on making the course form look better.
Any initiative from your side is also welcome

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/9846489/70378382-71e7d500-18fe-11ea-8abe-923e9663fbaa.png">

**Comment by silvadaniele** [comment]
We will deal with the 100% height in another ticket, as discussed.
